### ISSUE TITLE
Switch to soft tabs

### ISSUE THREAD

**Issue by philchristensen** [django-salesforce/django-salesforce#101]
We meant to do this months (years?) ago, but put it off because we were under active development. Things are pretty calm now, so I hope to do this ASAP.

**Comment by hynekcer** [comment]
I agree. I have currently about a hundred unapplied commits. I prefer to do it as the last change before v0.6 in order to prevent that everything would be a merge conflict.

**Comment by philchristensen** [comment]
That makes sense to me. There's a part of me that suspects it's unlikely to cause merge conflicts, but it would make history pretty messy.

**Comment by hynekcer** [comment]
Please move the milestone later. Support for Django 1.8 will require much more code than the previous versions and also to evaluate if my private older development branches can be used for master with it or not.

**Comment by philchristensen** [comment]
I've never been particularly religious about the tabs vs. spaces thing, but we might just have to bite the bullet and do it at some point.
