### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by johnnywell** [django-salesforce/django-salesforce#107]
I can't figure out what's wrong, because the only response I got is 
```json
{"error_description":"authentication failure","error":"invalid_grant"}
``` 
I could authenticate using curl --data with the same data I'm using in the application, so the data are fine. So I'm thinking it might be something in requests.post() since I got the same response by calling it directly.

**Comment by hynekcer** [comment]
This is a general message from Salesforce and very much questions/answers can be found for exactly the same message. An useful hint is that "security token" should be concatenated to the user's password, (Security token can be omitted if the local IP address has been whitelisted in Security Controls / Network Access.)

Can you confirm again that this fails?

    requests.post(settings_dict['HOST'] + '/services/oauth2/token', data=dict(
                    grant_type      = 'password',
                    client_id       = settings_dict['CONSUMER_KEY'],
                    client_secret   = settings_dict['CONSUMER_SECRET'],
                    username        = settings_dict['USER'],
                    password        = settings_dict['PASSWORD'],
                ))

and the same with curl succeeds?

    curl https://... -d grant_type=password -d client_id=... -d client_secret=... -d username=... -d password=...

**Comment by johnnywell** [comment]
Thanks for the quick answer.
Actually, I tried the same in production later and it worked, so I really have no idea what's going on, but it  worked in both cases using curl.
I'm not very familiar with Salesforce yet, maybe it requires any extra settings to authenticate on test environment?
