### ISSUE TITLE
Salesforce Disabling TLS 1.0 Encryption (..in 2016)

### ISSUE THREAD

**Issue by rwhitman** [django-salesforce/django-salesforce#109]
Just cleaning out my email inbox and wanted to make sure this is on the radar.

[This email from Salesforce](https://gist.github.com/rwhitman/4728ef2788c860d4282c) June 15 alerts that they are phasing out TLS 1.0 support

Not super familiar with the internal workings of django-salesforce or python's ssl packages but took a spin and spotted `ssl_version = ssl.PROTOCOL_TLSv1` in [adapter.py](https://github.com/django-salesforce/django-salesforce/blob/master/salesforce/backend/adapter.py). Not sure if it defaults to 1.1 or it needs to be named explicitly? Would this be an issue?

**Comment by philchristensen** [comment]
Well, the constants for the newer versions of TLS don't exist until Python 2.7.9. I'm not opposed to dropping 2.6 support, but I'm not sure how I feel about dropping pre-2.7.9 Python 2.7 support.

Of course, if there's no other option, it is what it is.

**Comment by hynekcer** [comment]
Yes, we must fix it.

The `request` package doesn't allow to specify what is the minimal required SSL version together with the directive to allow to use the highest SSL/TLS version available for both sides. ([requests issue 2118](https://github.com/kennethreitz/requests/issues/2118))  I think that it is more secure to require explicitely the lowest version supported by SFDC than to allow an arbitrary (old broken) version that can be false reported by "man in the middle" attacker as the highest supported by the server. I implemented the restriction after the last change made by SFDC and I did set it to curent TLS v 1.0. Now we must make the TLS version configurable and set the default version to TLS 1.1 to be easy to verify readiness of deploments of django-salesforce in advance.

The standard solution of TLS 1.1 and 1.2 for Python older than 2.7.9 is by installing additional packages:

    pip install pyopenssl ndg-httpsclient pyasn1

More information can be found in `requests` package in docs string `site-packages/requests/packages/urllib3/contrib/pyopenssl.py`

Now we must check the presence of `ssl.PROTOCOL_TLSv1_1` and recommend these packages if the constant is not found (that means Python is old).

**Comment by hynekcer** [comment]
Fixed.  
There is no reason to add that warning above. This installation seems entirely at the discretion of the user now.

**Comment by hynekcer** [comment]
I wrote tests for SSL/TLS in PR #119 with useful suggestions and additional logic if it fails.

I presume now that, though enabled SSL 3 is a big problem generally, it is not a big threat if we know that SFDC disabled that protocol completely without any "safe" downgrade mechanism. I can not reproduce the re-enabled SSL3 problem with pyOpenSSL again after writing more tests and compilated more Python versions etc. Yes, I know one way how pyOpenSSL can re-enable it, but it can be disabled now by more ways.
