### ISSUE TITLE
@override_settings doesn't play nicely with SALESFORCE_DB_ALIAS setting

### ISSUE THREAD

**Issue by hoprocker** [django-salesforce/django-salesforce#116]
In attempt to balance both completeness and speed, I have some tests which use a local datastore and some which reach out to Salesforce. I try to keep the Salesforce tests small -- just enough to test all of the required core functionality -- and then rely on the local datastore for testing more complex behavior. (This also helps with API usage limits.)

The natural way to do this is would seem to be with the `@override_settings(SALESFORCE_DB_ALIAS='')` decorator -- use this to set the salesforce db to the remote datastore *only* for connectivity tests, and leave it set to a local datastore the rest of the time.

I was coming up against a strange bug where column Ids weren't being set correctly. After some thinking and sleuthing, I found that at least part of the problem lies with how database alias-checking is done in django-salesforce: there are places where the alias is checked on load, and then never again (ie live changes won't affect it). Thus, any updating of the `settings` isn't going to be reflected (I assume this is copy-by-value).

I'll make up a pull request to demonstrate what I mean by this.

**Comment by hynekcer** [comment]
This can be accepted later. Yes, it is safe to switch between SFDC sandbox and sqlite database in memory, like automatic switch to the test database in other backentds. 
We have no robust mechanism yet that prevents writing to the production SFDC database in tests. I'm afraid of issues if some users would rely on only on these decorators.

What do you think about this warning in [Overriding settings](https://docs.djangoproject.com/en/1.8/topics/testing/tools/#s-overriding-settings) in Django docs:

> The settings file contains some settings that are only consulted during initialization of Django internals. If you change them with override_settings, the setting is changed if you access it via the django.conf.settings module, however, Django’s internals access it differently. Effectively, using override_settings() or modify_settings() with these settings is probably not going to do what you expect it to do...
> We do not recommend altering the **DATABASES** setting.

I see also in the source code of these decorators the word "hack" and warning about nested decorators etc. The worst bug would be writing from tests to production database.

The global variable sf_alias is used in more modules including in auth module. I would remove it and require  an explicit alias with authentication. I think that everything except tests should be the same: static or dynamic.

You can create a customized router with a property sf_alias:

-- my_module.py

    from salesforce.router import ModelRouter
    class MyModelRouter(ModelRouter):
        @property
        def sf_alias(self):
            return getattr(settings, 'SALESFORCE_DB_ALIAS', 'salesforce')

-- settings.py

    DATABASE_ROUTERS = ['my_module.MyModelRouter']

**Comment by hoprocker** [comment]
That's really informative, I didn't see that warning. Sounds like there's not much real benefit in altering things for the benefit of `@override_settings`, as it sounds like a tacked-on utility.

What I'm really after is a way to both test the connectivity with Salesforce, in a limited fashion, and then use a local testing database for the rest of the test suite. Your model router solution during testing would definitely do it. I'm going to close this out.

**Comment by hynekcer** [comment]
@hoprocker I'm writing something for migrations. I see that creation of the alternate test database is not easy enough. I think about backward compatibility. I expect that you use (must use) syncdb / migrate for creating the test database. Do you use an explicit "db_table" attribute for all models? Do you use the same complicated camel case Salesforce names and "__c" suffix for custom tables also in sqlite3?

**Comment by hoprocker** [comment]
With this current project, I'm stuck on Django 1.5.12 :-( All of the tables have both a `db_table` and `managed = True` attribute. My ORM schema was created using the `manage.py inspectdb` command.

I'm currently using a custom, overridden router in testing (as per your great suggestion). Things seem to be working pretty well.

**Comment by hynekcer** [comment]
Yes, it is easy if you don't use migrations for the alternate test database, otherwise also explicit attributes `db_column` must be used for custom models. I'm writing about it to docs. Many small changes in tha last PR are adressed by it.
