### ISSUE TITLE
none() method doesn't work on Salesforce models

### ISSUE THREAD

**Issue by chromakey** [django-salesforce/django-salesforce#124]
**This issue continues from PR #123** (edit: hynekcer)

Using the instructions from @hynekcer , I get a raise EmptyResultSet running both of the queries below on the test project:

```
Lead.objects.none()
Lead.objects.none().query.get_complier('salesforce').as_sql()
```

When I add my patch to the zip from pypi:

```
Lead.objects.none()
returns
[]
```

```
Lead.objects.none().query.get_compiler('salesforce').as_sql()
returns
raise EmptyResultSet
```

The project I'm working on where I stumbled upon this is a very basic CRUD front end for Salesforce leads, nothing interesting at all.  When I install my patch, it exhibits the same behavior as when I apply it to the test project.  

I'm using the Lead.objects.none() query in conjunction with a **django-filter**.  It works fine with non-salesforce models.

```
    filter = UserForm(queryset=User.objects.none())
    paginator = Paginator(filter.qs, 10)
    page = request.GET.get('page')

    try:
        paged_leads = paginator.page(page)
    except PageNotAnInteger:
        paged_leads = paginator.page(1)
    except EmptyPage:
        paged_leads = paginator.page(paginator.num_pages)
```

The above works fine using the django.contrib.auth User model.  However, the below returns a "salesforce.backend.base.SalesforceError: SOQL statements cannot be empty or null" error:

```
    filter = LeadFilter(queryset=Lead.objects.none())
    paginator = Paginator(filter.qs, 10)
    page = request.GET.get('page')

    try:
        paged_leads = paginator.page(page)
    except PageNotAnInteger:
        paged_leads = paginator.page(1)
    except EmptyPage:
        paged_leads = paginator.page(paginator.num_pages)

```
The forms are just simple
```
class UserForm(django_filters.FilterSet):
    class Meta:
        model = User

class LeadFilter(django_filters.FilterSet):
    class Meta:
        model = Lead
```
I am running django-salesforce 0.6, Python 3.4, and Django 1.7.8.

**Comment by hynekcer** [comment]
Please look at your traceback, find the line with the problematic queryset and put a debug print before it:

    print(my_queryset.query.get_compiler('salesforce').as_sql())

Repeat it until you find two lines that can be easily reproduced from django shell command line.
Your error is raiser between lines 39 - 49 in backend/query.py  
You can call debugger just before line 139

    newline   import pdb; pdb.set_trace()
    139       if(data['errorCode'] == 'INVALID_FIELD'):

That line is visited only after error. Press "u" Enter "p q, args" Enter   
and you will see the failed SOQL command

**Comment by hynekcer** [comment]
The EmptyResultSet exception is fixed.

If it doesn't solve your problem, you should investigate things around django-filter a little, as I wrote above, like it would be your code not your.

**Comment by chromakey** [comment]
Your patch seems to have resolved my issue.  The following code now executes correctly:
```
filter = LeadFilter(queryset=Lead.objects.none())
```
Thanks so much for your help!
