### ISSUE TITLE
Global name 'settings' is not defined

### ISSUE THREAD

**Issue by cmallon** [django-salesforce/django-salesforce#135]
When accessing certain models in the admin interface, am hit with this error.

It looks like manager.py is trying to access settings here:
**/site-packages/salesforce/backend/manager.py in using, line 46**

The quick patch seems to be adding:
**from django.conf import settings**
to that file.

In my settings file, I have declared the salesforce db alias to = "salesforce".

**Comment by hynekcer** [comment]
Thanks. It was a clear bug. I fixed it and I wrote a unit test. I only couldn't reproduce this bug in the admin. Fortunatily it is not important now..
