### ISSUE TITLE
inspectdb

### ISSUE THREAD

**Issue by abbad** [django-salesforce/django-salesforce#139]
I am using django 1.9 

I am trying to inspect the db and I for some reason I can't. Can someone help me with that please? 

Define a model that extends salesforce.models.Model or export the complete SF schema by python manage.py inspectdb --database=salesforce and simplify it to what you need.

Best Regards,
Ahmad Abbad

**Comment by chromakey** [comment]
Hi Ahmad,
Can you post the error you're receiving when you run the inspectdb command?

**Comment by abbad** [comment]
Ahmads-MacBook-Pro:Verse ahmadabbad$ python manage.py inspectdb 
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "***b/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "***lib/python3.5/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "****/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "***/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "****lib/python3.5/site-packages/django/core/management/commands/inspectdb.py", line 25, in handle
    for line in self.handle_inspection(options):
  File "****lib/python3.5/site-packages/django/core/management/commands/inspectdb.py", line 31, in handle_inspection
    connection = connections[options['database']]
KeyError: 'database'
()Ahmads-MacBook-Pro:Verse ahmadabbad$ python manage.py inspectdb --database=salesforce
Usage: manage.py inspectdb [options] 

Introspects the database tables in the given database and outputs a Django model module.

manage.py: error: no such option: --database

**Comment by chromakey** [comment]
```
python manage.py inspectdb --help
```
returns this optional argument
```
  --database DATABASE   Nominates a database to introspect. Defaults to using
                        the "default" database.
```

Try it without the "=".  i.e.

```
python manage.py inspectdb --database salesforce
```

This is a change from <= Django 1.8

**Comment by chromakey** [comment]
Actually it looks like both work (with and without the = sign).  Can you paste the DATABASES section of your settings? (be sure to obscure usernames/passwords)

**Comment by hynekcer** [comment]
Please, do you use the latest code from github? The update committed 4 days ago is important for Django 1.9

**Comment by abbad** [comment]
I just used pip install to get the package. Thank you :)

**Comment by hynekcer** [comment]
@philchristensen I think this issue would happen be repeated if we omit to release a new version. I wrote a few points to draft of v0.6.2. (I don't expect anything new important ready until mid-January.)

Thanks @chromakey for asking for information. I was easy then.

**Comment by philchristensen** [comment]
Ok, I should be able to get a new release out today.

**Comment by philchristensen** [comment]
Okay, I just pushed version 0.6.2 to pypi:

https://pypi.python.org/pypi/django-salesforce/0.6.2
