### ISSUE TITLE
Workaround the condition exclude(any_char_field='')

### ISSUE THREAD

**Issue by hynekcer** [django-salesforce/django-salesforce#143]
Never use the condition **`exclude(any_char_field='')`** for `CharField(null=True)`. This condition works only with fields with the attribute `null=False`.
Use `filter(any_text_field__gt='')` (that is an equivalent in all databases) 
or `exclude(any_text_field=None)` (that is the equivalent only in SFDC)

The same problem is with TextField, with all operators and also with a negated `Q(filter)` function: 
  `exclude(char_field__in=('', 'a'))` excludes only `'a'` 
  `exclude(char_field__lt='b'))` excludes only `'' < x < 'b'` 
  `filter(~Q(char_field=''))` is the same as exclude(char_field='') `

This problem is not related to fields that can never contain an empty string: numbers, booleans, dates, foreign keys etc. It is related only to fields that can save and keep both possible values `None` or `''` in Django. 

**Explanation:**
It is not a bug in django-salesforce, but a result of an incompatitility between ways, how Django and SFDC work with empty strings.

SFDC uses a strange logic `'' = null` for text fields, which is very problematic in negated SOQL  conditions:
- The `null` value is saved as empty string `''` to text fields.  
- SOQL evaluates WHERE conditions so that the empty string equals to both `null` and `''`
- The problem is that the negated filter `exclude(field=value)` in Django is equivalent to `NOT (field = value AND field IS NOT NULL)` if the field is defined with the attribute `null=True` in the django.db model, which is usual for a default Salesforce text field..

In the case of empty string, a queryset with `exclude(any_text_field='"")` is compiled to `NOT (field = '' AND field IS NOT NULL)` which is True in SOQL for all records, including the empty strings. It is equivalent to `.all()` in Django query set.

**Solution:**
The solution would be to use modified models with `null=False` for CharField and TextField. Also `inspectdb` should be modified accordingly.

**Comment by philchristensen** [comment]
Closing this issue, but added a link to it from the wiki here under important issues:

https://github.com/django-salesforce/django-salesforce/wiki#important-issues

**Comment by hynekcer** [comment]
I think that a solution exists if we would map Force.com NULL string to Django empty string and vice versa. It would require a new character type field with attribute null=False, that means no null on the Django side. Also `default=''`. This is not a priority, currently I should examine null in soap api, it is even not clear if it would work good with raw queries etc. I agree with the idea of wiki, but it should be a helpful clear paragraph, not a link back there. I prefer reopen.

**Comment by philchristensen** [comment]
Sorry, I should have touched base before closing.

**Comment by hynekcer** [comment]
Closing. A wiki about [Empty strings in filters](https://github.com/django-salesforce/django-salesforce/wiki/Empty-strings-in-filters) bas been written.
