### ISSUE TITLE
Can't fetch objects with multiple levels of reverse lookup

### ISSUE THREAD

**Issue by johnnywell** [django-salesforce/django-salesforce#144]
I'm trying to query a multiple level reverse lookup, 2 levels to be precise.

```python
Case.objects.filter(veiculo__avl__name="A0000320")
```
The ForeignKeys are like:
Case --> Veiculo
Avl --> Veiculo

But I'm getting the following exception:
```python
Internal Server Error: /data-table/4
Traceback (most recent call last):
  File "/home/johnny/Workspace/doutor-inlog/doutor_inlog/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/johnny/Workspace/doutor-inlog/doutor_inlog/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/johnny/Workspace/doutor-inlog/doutor_inlog/app/olho_vivo/views.py", line 313, in data_table
    data = get_packets(server, start_date, end_date)
  File "/home/johnny/Workspace/doutor-inlog/doutor_inlog/app/olho_vivo/views.py", line 118, in get_packets
    for case in cases:
  File "/home/johnny/Workspace/doutor-inlog/doutor_inlog/venv/lib/python3.4/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/home/johnny/Workspace/doutor-inlog/doutor_inlog/venv/lib/python3.4/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/johnny/Workspace/doutor-inlog/doutor_inlog/venv/lib/python3.4/site-packages/salesforce/backend/query.py", line 265, in iterator
    sql, params = SQLCompiler(self.query, connections[self.db], None).as_sql()
  File "/home/johnny/Workspace/doutor-inlog/doutor_inlog/venv/lib/python3.4/site-packages/salesforce/backend/compiler.py", line 140, in as_sql
    soql_trans = self.query_topology()
  File "/home/johnny/Workspace/doutor-inlog/doutor_inlog/venv/lib/python3.4/site-packages/salesforce/backend/compiler.py", line 288, in query_topology
    (top_lhs,) = set(side_l).difference(side_r)
ValueError: too many values to unpack (expected 1)
```
I'm using python 3.4 and Django 1.9.

**Comment by chromakey** [comment]
Hi Johnny,
Can you help us better understand your model relationships and the result you're hoping to get?  

Are you saying that one Case has many Veiculos and one Avl can also have many Veiculos?

Are you trying to select the relevant Case objects where the one of the Case's Veiculos has an Avl with the name of A000320? 

Just trying to better understand what you're to do so I can troubleshoot clearly.  Thanks so much.

**Comment by hynekcer** [comment]
You can be sure that it is supported. Up to 5 levels from children to the parent object can be used in filters, a branched "genealogy" is possible, the same object types can be repeated more times, but the filters must correspond to the relationship hierarchy. This is probably your problem.

**Comment by johnnywell** [comment]
Actually the ForeignKeyFields could be OneToOneFields since, one case has just one Veiculo and an Avl is installed in just one Veiculo as well.

My current models are something like:

```python
class Case(Model):
    veiculo = models.ForeignKey('Veiculo', models.DO_NOTHING, db_column='Ve_culo__c', blank=True, null=True)

class Avl(Model):
    veiculo = models.ForeignKey('Veiculo', models.DO_NOTHING, db_column='Ve_culo__c', blank=True, null=True)

class Veiculo(Model):
    identificador = models.CharField(db_column='Identificador__c', max_length=12)
```

**Comment by hynekcer** [comment]
Salesforce use only thee builtin one-to-one relationships: two times relationship to FeedItem and one relationship from ApexEmailNotification to User. Nobody can create a custom one-to-one relationships.

I remember from Salesforce forums that it is mostly recommended to set one direction by a lookup field or master detail relationship field, both variants with "unique Id" checkbox, plus to set a reverse lookup field, (e. g. by a trigger for insert/update/delete and set this field read-only for users).

```
class Avl(Model):
    veiculo = models.ForeignKey('Veiculo', models.DO_NOTHING, db_column='Ve_culo__c', blank=True,
            null=True, unique=True)    # add unique

class Veiculo(Model):
    identificador = models.CharField(db_column='Identificador__c', max_length=12)
    avl = models.ForeignKey('Avl', models.DO_NOTHING, db_column='Avl__c', blank=???,
            null=???)
```

Then your query set will work.

Salesforce doesn't allow to set a where condition on parent based an a children set field. [see SOQL](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_relationships.htm)

But you can solve it by a subquery, even wihout the redundant reverse relationship:

    Case.objects.filter(veiculo=Avl.objects.get(name="A0000320").veiculo)
    # or
    Case.objects.filter(veiculo__in=[x.veicolo for x in Avl.objects.filter(name="A0000320").veiculo])

The first variant can be used if you search only one Avl with a unique name.

So, we can improve something like the error message, but this is an issue for Salesforce, not for this project and we can do nothing with the core of the problem.

---

> Actually the ForeignKeyFields could be OneToOneFields since, one case has just one Veiculo and an Avl is installed in just one Veiculo as well.

You explained in other words that it is not a many-to-many relationship, but it still can be a many-to-one relationships if you did not say also that one Veicolo can have only one Avl. I didn't know your model, if Veicolo and Avl are meant objects for type designations or individual pieces e.g. with a serial number. So both understanding was still possible for me.

**Comment by johnnywell** [comment]
You are right, the mess in the Salesforce tables and my lack of Knowledge about Salesforce at all, contributes to fails like this.

Putting the ForeignKey on the Veiculo solved the exception, but I'm getting a strange behavior.
When I query for ```Avl.objects.get(veiculo__name="ACU-0535")``` I get the expected Avl, but when I do like  ```Veiculo.objects.get(avl__name="A0000320")``` I get a DoesNotExist exception.

Any idea why this is happening?

**Comment by hynekcer** [comment]
If the Avl could be created only by Django (not true) you can create the two mutual relations this way:

    # demo - not meat seriously 
    veiculo = Veiculo.objects.get(...)
    avl = Avl(veiculo=veiculo,...)
    avl.save()
    veiculo.avl = veiculo
    veiculo.save()
   
But you probably can not garantee that nobody will modify one of them manually. A trigger could be written, but it is also fragile or finally too complicated.

I also made a mistake in the previous answer, because no unique custom foreign key is possible in Salesforce. I'm going to fix it.

**Comment by johnnywell** [comment]
The thing is that it's not created just through Django, The operation through Salesforce is already something huge. I would have to run over all those records and enforce this relation.

**Comment by hynekcer** [comment]
The solution with a subquery is easier now and maybe be sufficient. My expirience is, don't rely on duplicit fields if the data can be supplied manually, until the database has a prepared good mechanism to continously preserve the integrity of the data in every moment.

The solution with a reverse relation still doesn't enforce the uniquenes of the foreign key. That is more important. It would be a confusion if the expected one-to-one relation wouldn't be one-to-one by accident.

If many rows must be updated by API now, you can be restricted by Salesforce governor limits per 24 hours. Look at: Salesforce / Setup / Monitor / System Overview / API Usage, what is your available maximum and how many requests remain, otherwise all APIs calls would be blocked for 24 hours without a possibility to run even one query. The new column can by imported by a CSV file (Id, Avl columns) or by bulk API and it consumes only one request per 10000 rows.

**Comment by johnnywell** [comment]
Yeah, thanks a lot guys, I'll put some effort to investigate it now.
