### ISSUE TITLE
Import issue when using manage.py runserver with GAE

### ISSUE THREAD

**Issue by chrisadams** [django-salesforce/django-salesforce#168]
Hello, dumb person here. I'll close this issue myself in a while but just wanted to ask this question to see if anyone has an idea.

I have a working solution that GETs and POSTS to my SFDC instance when I run my application locally via a python script. But now that I'm trying to deploy my application to GAE and use routing and templating I am running into issues. I'm working off of https://github.com/GoogleCloudPlatform/appengine-django-skeleton.

I get errors when I load any page after running `python manage.py runserver` or using the GAE provided webserver dev_appserver.py.

I get:

```
Traceback (most recent call last):
  File "/Applications/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/Users/chrisa/standard_django_hello_world/customer_data_salesforce/lib/django/core/handlers/wsgi.py", line 165, in __call__
    signals.request_started.send(sender=self.__class__, environ=environ)
  File "/Users/chrisa/standard_django_hello_world/customer_data_salesforce/lib/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/chrisa/standard_django_hello_world/customer_data_salesforce/lib/django/db/__init__.py", line 55, in reset_queries
    for conn in connections.all():
  File "/Users/chrisa/standard_django_hello_world/customer_data_salesforce/lib/django/db/utils.py", line 227, in all
    return [self[alias] for alias in self]
  File "/Users/chrisa/standard_django_hello_world/customer_data_salesforce/lib/django/db/utils.py", line 212, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/chrisa/standard_django_hello_world/customer_data_salesforce/lib/django/db/utils.py", line 135, in load_backend
    raise ImproperlyConfigured(error_msg)
ImproperlyConfigured: 'salesforce.backend' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
Error was: No module named backend.base
INFO     2016-10-21 20:58:32,559 module.py:788] default: "GET / HTTP/1.1" 500 -
INFO     2016-10-21 20:58:33,154 module.py:402] [default] Detected file changes:
  /Users/chrisa/standard_django_hello_world/customer_data_salesforce/mysite
```

My settings.py looks like:

```
DATABASES = {
    'default': {
     'ENGINE': 'django.db.backends.mysql',
     'HOST': <redacted for github>
     'NAME': 'db',
     'USER': 'pythonapp',
     'PASSWORD':  <redacted for github>,
    },
    'salesforce': {
        'ENGINE': 'salesforce.backend',
        "CONSUMER_KEY":  <redacted for github>,
        "CONSUMER_SECRET":  <redacted for github>,
        'USER':  <redacted for github>,
        'PASSWORD':  <redacted for github>,
        'HOST': 'https://login.salesforce.com',
    },
```

It has 'salesforce' in installed_apps and I included the snippet to add the router.

If I put `import salesforce` in my code it works fine but if I use `import salesforce.backend`or `from salesforce include backend` I get an import error.

Any ideas?

**Comment by philchristensen** [comment]
Hi Chris. This looks like an issue specifically with the GAE shim you're using. I'd suggest raising this issue over there. Custom backends like our aren't strictly supported by Django, so they may have made some assumptions about what the content of the ENGINE paean should be.

**Comment by hynekcer** [comment]
It is very strange and very useful what you reported recently because the file `salesforce/backend/__init__.py` contains only two commands that could theoretically fail `import logging` and `log = logging.getLogger(__name__)`, but that is very very improbable. It is so simple that it can be imported even before anything is configured. I think that the only explanation is that the imported module `salesforce` is not from our package.
Try to run `import salesforce`; `print(salesforce)` or write the value to the log. You can do it even directly in the file `wsgi.py`. Also `print(sys.path)` is useful.

**Comment by philchristensen** [comment]
"they" being the authors of the GAE shim

**Comment by hynekcer** [comment]
I lave looked at *appengine-django-skeleton*. It uses a normal Django 1.9 since December 2015 if a *Cloud SQL* is used like MySQL with normal mysql backend. I seems that it should work with django-salesforce. However it is right that in case of alternative alternative *Cloud Datastore*, a patched Django (djangae) is required and it very probably can't work with django-salesforce because all standard backends are removed except the supported *appengine*.

**Comment by philchristensen** [comment]
"Djangae", I like that!

**Comment by chrisadams** [comment]
My sys.path is:
```
['/Users/chrisa/standard_django_hello_world/customer_data_salesforce', '/Users/chrisa/standard_django_hello_world/customer_data_salesforce/lib', '/Applications/google-cloud-sdk/platform/google_appengine', '/Applications/google-cloud-sdk/platform/google_appengine', '/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Applications/google-cloud-sdk/platform/google_appengine/lib/MySQLdb-1.2.5', '/Applications/google-cloud-sdk/platform/google_appengine/lib/protorpc-1.0', '/Applications/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3', '/Applications/google-cloud-sdk/platform/google_appengine/lib/webob-1.1.1', '/Applications/google-cloud-sdk/platform/google_appengine/lib/yaml-3.10']
```

and `import salesforce; print(salesforce)` gives me: `<module 'salesforce' from '/Users/chrisa/standard_django_hello_world/customer_data_salesforce/salesforce/__init__.pyc'>`

**Comment by hynekcer** [comment]
OK, even that you have confirmed still a small part of my notes. You could be more active and inventive it the verification process what your cloud account is doing if you want succeed. Do you use django-salesforce 0.6.9? It is very slow for me to remember the problem if you try four days to import an "empty" (not entirely empty) file and you have no final result yet.

Verify that you try to import [the expected file contents](https://raw.githubusercontent.com/django-salesforce/django-salesforce/ec3738245ecee56b1f5fa030f021a54f5ac1d0b3/salesforce/backend/__init__.py) that should be in `/Users/chrisa/standard_django_hello_world/customer_data_salesforce/salesforce/backend/__init__.py` (its size is 1365 or explore what is in) and  that the user running the app (you?) can read the file.

What is `from salesforce include backend`? (SyntaxError not ImportError) Do you mean "import"? Please verify again what you wrote.

(I guess that you evaluate this as an invalid issue soon, but you can find later a real problem with GAE, for a new issue, if you have the ability to be a pioneer. I recommend to send any potentially excessive useful information like tracebacks, versions etc.  by http://dpaste.com/ and put a link. I will copy the relevant info and the rest is removed after the period that you selected.)

**Comment by chrisadams** [comment]
I'm sorry for not responding sooner.

Those are the same contents that I have at `/Users/chrisa/standard_django_hello_world/customer_data_salesforce/salesforce/backend/__init__.py`. 

Sorry `from salesforce include backend` was a typo on this GitHub issue, but in my code I'm trying `from salesforce import backend`, which gives a `ImportError: cannot import name backend`.

**Comment by chrisadams** [comment]
I found the issue, it was a namespace conflict. Totally my fault not django-salesforce or google.

**Comment by chrisadams** [comment]
Thanks for all of your help @hynekcer and @philchristensen
