### ISSUE TITLE
Preparing for Django 2.0

### ISSUE THREAD

**Issue by hynekcer** [django-salesforce/django-salesforce#199]
I'm starting to prepare for Django 2.0. One of first steps will be to restrict supported versions to Django 1.10, 1.11+ and fix the features that worked only before 1.10, but not now, especially the things related to deferred fields like values(), values_list(), defer(), only() methods.

**Comment by dhbahr** [comment]
Nice one, @hynekcer ! Would this include fixing (not sure if this worked prior to 1.10) invoking `delete` on a SalesforceQuery object?

**Comment by hynekcer** [comment]
Yes, if we drop support for 1.8 and 1.9, it can.

**Comment by masterfloda** [comment]
IMO you should drop support for all outdated Django versions. 1.9 and 1.10 have already run out of extended support and 1.8 LTS will on April 1st 2018, so I wouldn't bother with it. But I would really appreciate Django 2.x compatibility :-)

**Comment by philchristensen** [comment]
Closing in favor of #211 and PR #217
