### ISSUE TITLE
Example default models

### ISSUE THREAD

**Issue by masterfloda** [django-salesforce/django-salesforce#208]
Not an issue but a question / feature request:

I am too lazy to create the models myself :-) Can someone provide a base class with the common fields and maybe even the models for the default objects, like User, Case, Account, Opportunity, etc?
Maybe it could be included in an example file in the src.

**Comment by philchristensen** [comment]
inspectdb works normally with django-salesforce, so that’s the easiest way to generate the model code.

**Comment by philchristensen** [comment]
https://github.com/django-salesforce/django-salesforce/wiki/Introspection-and-Special-Attributes-of-Fields

**Comment by philchristensen** [comment]
python manage.py inspectdb --database=salesforce

**Comment by masterfloda** [comment]
We have bazillions of custom fields and reducing them to what I actually need might become a bit tiresome. I thought there might be an even simpler solution :-) Thanks anyway!
