### ISSUE TITLE
Bug when saving a PersonAccount

### ISSUE THREAD

**Issue by dhbahr** [django-salesforce/django-salesforce#209]
When trying to save a PersonAccount, SF complains about being unable to update the `Name` field, which makes perfect sense. How should I proceed in this case? Is there a way of telling the manager that this field should not be writable?

```
    Request Method: POST
       Request Url: https://******
    Django Version: 1.11.3
    Exception Type: SalesforceError
   Exception Value: Unable to create/update fields: Name. Please check the security settings of this field and verify that it is read/write for your profile or permission set.
Exception Location: .env/lib/python3.5/site-packages/salesforce/backend/driver.py in handle_api_exceptions, line 186
 Python Executable: .env/bin/python3
    Python Version: 3.5.2
      Python Path : ['.env/bin',  '.env/lib/python35.zip',  '.env/lib/python3.5',  '.env/lib/python3.5/plat-x86_64-linux-gnu',  '.env/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '.env/lib/python3.5/site-packages']
       Server Time: Mon, 19 Mar 2018 15:48:12 +0000
```

Best

**Comment by philchristensen** [comment]
I believe you'll want to add one of the attributes described here:

https://github.com/django-salesforce/django-salesforce/wiki/Introspection-and-Special-Attributes-of-Fields

I think you want `sf_read_only=models. NOT_UPDATEABLE`

**Comment by dhbahr** [comment]
Does this apply per record so that I can make it conditional? The thing is I need the attribute (`name`) to be writable for regular accounts, and read-only for person accounts only.

**Comment by philchristensen** [comment]
Ah, I see. I think to achieve that you'll need to override the save() method.

**Comment by dhbahr** [comment]
I managed to bypass it for now passing the `update_fields` parameter on the `save` method, but that would become an issue in the long run, so your suggestion will probably be a better solution.

Thanks!

Best
