### ISSUE TITLE
Support for Django 2.x

### ISSUE THREAD

**Issue by dhbahr** [django-salesforce/django-salesforce#211]

**Comment by philchristensen** [comment]
At this time the general goal of @hynekcer and myself is to keep the library functioning for its existing users. The last time we discussed Django 2.0 there was expected to be a lot of changes at the db level that are entirely incompatible with the existing approach.

There are no Django 2.0+ initiatives underway that I know of.

**Comment by benjaminrigaud** [comment]
Do you have a list of all the changes required? Do you think it is feasible? I would be happy to help / do the work.

**Comment by philchristensen** [comment]
Sorry, nothing like that that I know of.

**Comment by benjaminrigaud** [comment]
I'll give it a go then. See if it looks feasible.

**Comment by philchristensen** [comment]
You'll need a valid SF account to test with, but a developer account is enough.

**Comment by jgb** [comment]
@philchristensen I'm a colleague of @benjaminrigaud and we're trying to get the test suit to run using tox, but no luck so far. We tried using a salesforce developer account that we created for this purpose. This is the content of our local_settings.py:
```
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': 'salesforce_testrunner_db',
	},
	'salesforce': {
		'ENGINE': 'salesforce.backend',
		"CONSUMER_KEY" : 'xxx',
		"CONSUMER_SECRET" : 'xxx',
		'USER': 'xxx',
		'PASSWORD': 'password + token concatenated',
		'HOST': 'https://test.salesforce.com',
	}
}

SALESFORCE_QUERY_TIMEOUT= (4, 15)
```

This is the error we're getting:

```
======================================================================
ERROR: test_lead_conversion (salesforce.tests.test_utils.UtilitiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jan/clones/django-salesforce/salesforce/tests/test_utils.py", line 29, in test_lead_conversion
    lead.save()
  File "/home/jan/clones/django-salesforce/.tox/py36-dj111/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/jan/clones/django-salesforce/.tox/py36-dj111/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/jan/clones/django-salesforce/.tox/py36-dj111/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/jan/clones/django-salesforce/.tox/py36-dj111/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/jan/clones/django-salesforce/.tox/py36-dj111/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jan/clones/django-salesforce/.tox/py36-dj111/lib/python3.6/site-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/jan/clones/django-salesforce/salesforce/backend/compiler.py", line 419, in execute_sql
    with self.connection.cursor() as cursor:
  File "/home/jan/clones/django-salesforce/salesforce/backend/base.py", line 185, in cursor
    cursor = CursorWrapper(self, query)
  File "/home/jan/clones/django-salesforce/salesforce/backend/query.py", line 434, in __init__
    self.session = db.sf_session
  File "/home/jan/clones/django-salesforce/salesforce/backend/base.py", line 146, in sf_session
    self.make_session()
  File "/home/jan/clones/django-salesforce/salesforce/backend/base.py", line 135, in make_session
    sf_instance_url = sf_session.auth.instance_url
  File "/home/jan/clones/django-salesforce/salesforce/auth.py", line 144, in instance_url
    return self.get_auth()['instance_url']
  File "/home/jan/clones/django-salesforce/salesforce/auth.py", line 118, in get_auth
    oauth_data[db_alias] = self.authenticate()
  File "/home/jan/clones/django-salesforce/salesforce/auth.py", line 198, in authenticate
    raise LookupError("oauth failed: %s: %s" % (settings_dict['USER'], response.text))
LookupError: oauth failed: xxx: {"error":"invalid_grant","error_description":"authentication failure"}
```

Any idea what we might be doing wrong?
I followed all of the advice I found online related to salesforce, about relaxing ip restrictions and so on, nothing seems to help.
The funny part is when I simply try to login via curl with the same credentials it works fine.

**Comment by dhbahr** [comment]
@jgb is it safe to assume you created the respective Connected App in the Salesforce Org?

**Comment by dhbahr** [comment]
Also, if it is a Developer Org, the login url should be https://login.salesforce.com, not test.salesforce.com.

**Comment by jgb** [comment]
Ok thanks @dhbahr that gets me one step further!
However now all tests fail with a traceback similar to this one:

```
ERROR: test_not_null_related (salesforce.tests.test_integration.BasicSOQLRoTest)
Verify conditions `isnull` for foreign keys: filter(Account=None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jan/clones/django-salesforce/salesforce/tests/test_integration.py", line 261, in test_not_null_related
    test_contact.save()
  File "/home/jan/clones/django-salesforce/.tox/py36-dj111/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/jan/clones/django-salesforce/.tox/py36-dj111/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/jan/clones/django-salesforce/.tox/py36-dj111/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/jan/clones/django-salesforce/.tox/py36-dj111/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/jan/clones/django-salesforce/.tox/py36-dj111/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jan/clones/django-salesforce/.tox/py36-dj111/lib/python3.6/site-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/jan/clones/django-salesforce/salesforce/backend/compiler.py", line 423, in execute_sql
    cursor.execute(sql, params)
  File "/home/jan/clones/django-salesforce/salesforce/backend/query.py", line 463, in execute
    response = self.execute_insert(self.query)
  File "/home/jan/clones/django-salesforce/salesforce/backend/query.py", line 562, in execute_insert
    return handle_api_exceptions(url, self.session.post, headers=headers, data=json.dumps(post_data), _cursor=self)
  File "/home/jan/clones/django-salesforce/salesforce/backend/driver.py", line 191, in handle_api_exceptions
    raise SalesforceError('%s' % data, data, response, verbose)
salesforce.backend.driver.SalesforceError: {'message': 'INVALID_HEADER_TYPE', 'errorCode': 'INVALID_AUTH_HEADER'}
```

**Comment by dhbahr** [comment]
hmm .. that's a first timer.
Can you maybe try to inspect the headers being used?

**Comment by jgb** [comment]
I put a try/except around one of the failing tests, and managed to come up with this, not sure if it's what you are looking for?

```
(Pdb) self.getheaders()
HTTPHeaderDict({'Date': 'Wed, 24 Oct 2018 14:46:10 GMT', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': 'upgrade-insecure-requests ', 'X-Robots-Tag': 'none', 'Cache-Control': 'no-cache,must-revalidate,max-age=0,no-store,private', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked'})
```

**Comment by dhbahr** [comment]
Seems to be what I asked for, unfortunately I cannot say I have a clear idea of what's failing. The most noticeable detail is that there seems to be no "Authorization" header in the dict.
Not sure at which point in the stacktrace this is the value for the dict, but I was specifically interested on the value at this point:

```
File "/home/jan/clones/django-salesforce/salesforce/backend/query.py", line 562, in execute_insert
    return handle_api_exceptions(url, self.session.post, headers=headers, data=json.dumps(post_data), _cursor=self)
```

I'm very sorry for not being clearer to begin with.

**Comment by jgb** [comment]
I failed to notice earlier that this gets printed when it goes wrong, is that what you're looking for?

```
E.........Error (debug details) [{"message":"INVALID_HEADER_TYPE","errorCode":"INVALID_AUTH_HEADER"}]
{'_content': b'[{"message":"INVALID_HEADER_TYPE","errorCode":"INVALID_AUTH_HEADER"}]', '_content_consumed': True, '_next': None, 'status_code': 401, 'headers': {'Date': 'Wed, 24 Oct 2018 15:44:57 GMT', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': 'upgrade-insecure-requests ', 'X-Robots-Tag': 'none', 'Cache-Control': 'no-cache,must-revalidate,max-age=0,no-store,private', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked'}, 'raw': <urllib3.response.HTTPResponse object at 0x7fe3ec90fa58>, 'url': 'https://eu16.salesforce.com/services/data/v39.0/sobjects/Lead/', 'encoding': 'UTF-8', 'history': [], 'reason': 'Unauthorized', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(0, 0, 146351), 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x7fe3ec95b9e8>}
```

**Comment by dhbahr** [comment]
Hmm .. this seems to be more the response object than the request. Maybe you could add a quick debugging point on `File "/home/jan/clones/django-salesforce/salesforce/backend/query.py", line 561` and inspect the value of the `headers` variable at that point?

**Comment by jgb** [comment]
headers turns out to be very minimal:
```
{'Content-Type': 'application/json'}
```

**Comment by FlipperPA** [comment]
@jgb @dhbahr My organization is interested in getting this working for Django 2.0 as well. Any chance we can get a branch somewhere? We'd like to be able to pull down what you've done so far, and contribute via PRs. Thanks for your efforts so far!

**Comment by philchristensen** [comment]
Hey guys, just saying that although I can’t contribute materially to the code, I’m glad to help review issues and PRs or any other project work.

**Comment by silviogutierrez** [comment]
@philchristensen @hynekcer: like others, I'm interested in seeing this library work with 2.0+

Any chance of making this happen for a paid engagement? Of course, changes would be open sourced upstream, so everyone benefits.

**Comment by jbaack** [comment]
Like everyone else, I am interested in 2.0+ support. I am very new to Django, so not familiar at all with this code or changes that occurred in 2.0. I have a simple setup now working with 2.1.3 that is able to run inspectdb and then with the full generated set of models, run the admin and create, update and delete records for the few object types I have tried. The code changes were simple and minimal and I can share them if that would be useful. I have not attempted to run the tests or exercise any advanced capabilities and I have no doubt my changes will NOT be sufficient to provide full 2.0+ compatibility - nor do they provide backward compatibility to 1.x, although that should be straightforward. The code works for my needs at this time.

**Comment by philchristensen** [comment]
@jbaack PRs are always appreciated. I don’t even really have a baseline right now for what works and what doesn’t, except for this thread, really.

@silviogutierrez Thanks very much. That kind of support is always appreciated, but unlikely to make a difference in this case.

**Comment by datatalking** [comment]
We have a Django project and I'm also interested in working as a debugger, developer and django developer of features on this.

Are there any screen shots in the repo to see what the django interface with this all running is? (outside of this bug of course)

**Comment by dhbahr** [comment]
@FlipperPA I myself don't have any forks of this project (would love to be able to work on it, but have no time to put on it, specially in the past couple of months). I apologize for the delayed followup. I am pretty sure though that @philchristensen would be keen on integrating any pull requests you send this way as long as they push the library forward, since this is the official repo that would mean changes making it upstream (pip and so on) rather sooner than starting a spin-off somewhere else.

Cheers

**Comment by hynekcer** [comment]
@silviogutierrez Thanks very much. Financing the project is currently a fundamental issue for me, because at the moment, if I should continue, I would have to be sure that I can start to employ a person to whom I would hand over some of my other simpler current activities. The time requirement of update for Django 2.0+ is approximately one half of all previous time requirements. It is possible to also refactor the package later so that future updates will be much easier (especially to not use undocumented Django internals that simplified the package very much, but they are continuously changing), it would require even more certainty for the future of the project. I see that it is not realistic to be waiting for more free time incidentally.

**Comment by silviogutierrez** [comment]
@hynekcer : thanks and makes sense. I will email you and see if we can work something out. Please look at our for an email from this same username @ well known "don't-be-evil" corporation.

**Comment by philchristensen** [comment]
I'm really pleased to say that thanks to everyone's interest, @hynekcer has been able to make some headway on #217 along with several of @jbaack's changes.

It will probably be a little while before a formal release, but this will be the start of the v0.8 series.

**Comment by philchristensen** [comment]
Just merged #217 and #219 (a fix for #210) into master. A new release is imminent in the next week or so.

**Comment by hynekcer** [comment]
Version 0.8 with support for Django 2.1 is prepared in PR #222. Please test it that it can be released in this form. It was a hard work with many refactoring as never before in this project.

**Comment by philchristensen** [comment]
Thanks again for all your hard work @hynekcer

**Comment by MounirMesselmeni** [comment]
@philchristensen Any plan for a release date?

**Comment by philchristensen** [comment]
I’m hoping for a release in the next day or two. For various reasons discussion for that ended up on #225

Release notes are written, tests are passing, just making sure everything is ready for release.

**Comment by hynekcer** [comment]
Tomorrow by @philchristensen ?, and my last simple commits today, if we postpone documentation for some new features. The documentation is used mostly on the web that can be easier updated. I was waiting for a feedback about regressions since February 7th and no problem has been reported. I worked on features for a new release. Today I'm checking for areas of possible backward incompatibilities that are probably not used by anybody, but should be in release notes.

**Comment by philchristensen** [comment]
Pleased to officially announce the release of v0.8, the culmination of a lot of great work by @hynekcer and the rest of our community. See release notes here:

https://github.com/django-salesforce/django-salesforce/releases/tag/v0.8

Closing this ticket with much satisfaction...
