### ISSUE TITLE
Can you provide examples

### ISSUE THREAD

**Issue by datatalking** [django-salesforce/django-salesforce#215]
This is very close to a project we've been building.

Could someone post screenshots of what this implementation looks like?

It seems to be a django cms implementation of the salesforce api but I can't see what it creates and rather than going through the whole installation and configuration to find out it doesn't do it.

Please post photos of this installed.

I'm curious to help out and debug this as it seems very close to what I was planning.

**Comment by hynekcer** [comment]
This is a database backend and text examples of queries and responses are more typical than screenshots in a documentation for similar products, but I understand you. The documentation for Python, Django or SQL databases looks like a text with many screenshots, but it is internally a formatted text. Probably both simple usual examples and also short examples of the most complex supported queries should be added. If you agree I rename "screenshots" to "Can you provide examples".

**Comment by hynekcer** [comment]
Some advanced examples of more complicated supported Django querysets are here. I'm mot sure if you are interested in simple or advanced examples.

**Comment by philchristensen** [comment]
This is not a CMS in any sense of the word. I think we're pretty clear that this is a database backend for Django.
