### ISSUE TITLE
Query Custom Objects

### ISSUE THREAD

**Issue by Dssii3056** [django-salesforce/django-salesforce#235]
Hello,

I'm sorry for the wall of text. Thank you in advance to anyone to took the time to read this.

I'm getting started with django-salesforce, and I'm having trouble looking up two items in the documentation.

**### 1. How do I query a custom object?** 

When I attempt to create a _models.SalesforceMode_l using the name _manage.py inspectdb_ provided, I'm encountering a seemingly obvious issue with custom_objects__c in Salesforce.

If my model is named Applications => then my query would look something like this 

**Applications.objects.filter(account_name = self.request.user.SFPK)**

But the query is interpreted as below, which is WAY OFF
**Applications.AccountName__c FROM Applications WHERE Applications.AccountName__c**

I would like for this query to be structured as 

**SELECT name ,Date_Submitted__c,Status__c, Approval_Amount__c, Account_Name__c
FROM Applications__c
WHERE Account_Name__c = 'self.request.user.SFPK'**

So there are two things happening that I'm having trouble looking up in the documentation.

1. The query is prefixing the object name **Applications**.custom_field__c to the variables in the class
2. The query does not append '__c' to the Object it is querying, and typing __c to the class name or in the query gives me an error

**applications.Applications__c: (models.E024) The model name 'Applications__c' cannot contain double underscores as it collides with the query lookup syntax.**

Are there any examples of queries of custom objects? Or more specifically a custom object query with a filter? How do I handle the class name without a double under__score (which causes a Django Error)

### **2. How to set query filters from within the manage.py shell?**

Your documentation was wonderful to get me started on running test queries to SF

**python manage.py inspectdb --database=salesforce**

However, I'm having trouble with the examples in documentation testing queries from within the shell where the django environment is running...the code samples appear to be running from within PYTHON, not bash/etc.

For the example:
**my_qs = Contact.objects.filter(my__little_more__complicated='queryset')
print(str(my_qs.query))       # that recognizes that the query should be compiled to SOQL**

If I substitute

 **λ my_qs = Contact.objects.filter()**

Result == **my_qs' is not recognized as an internal or external command,
operable program or batch file.**

If I run the command from python manage.py shell I also receive errors

name 'Contact' is not defined

### example .model & .view for 1
------------------------.model----------------------------
 class Applications(models.SalesforceModel):
	name = models.CharField(max_length=80)
	date_submitted = models.CharField(max_length=40, custom=True)
	status = models.CharField(max_length=40, custom=True)
	approval_amount = models.CharField(max_length=40, custom=True)
	account_name = models.CharField(max_length=40, custom=True)

	class Meta:
		managed = False
		abstract = False

	def __str__(self):
		return self.name
------------------------.view----------------------------
class ApplicationsListView(LoginRequiredMixin, ListView):
	model = Applications
	template_name = 'applications_list.html'
	login_url = 'login'
	def test_func(self):
		obj = self.get_object()
		return obj.account_name == self.request.user.SFPK

	def get_queryset(self):
		user = self.request.user
		queryset = Applications.objects.filter(account_name = self.request.user.SFPK)
		querysetString = str(queryset.query)
		return querysetString
--------------------end-------------

Thank you again for supporting this wonderful tool. I really hope to familiarize myself with it some more.

**Comment by philchristensen** [comment]
It looks like your issues are largely related to Django and Python, not really Django-Salesforce. There's a certain expectation that users of this package will know both those platforms quite well.

1.) The Django ORM doesn't give you the kind of precise control over queries that you're thinking. However, if you add `db_table="Applications__c"` to the Meta class for the object this should query the custom object properly. Also, if you really want it to query `name` and not `Name` you can do so with the `db_column` parameter on the field class. These are standard Django conventions.

2.) You haven't imported the names you're using in the shell sample. The sample code is just a starting point; it doesn't generally include import statements for common things, like your model classes, because we wouldn't know what the name of your module is to import from.

A cursory review of your code shows a number of other fundamental errors with your views, such as returning a string from `get_queryset()` instead of the queryset you created.

You might want to spend some time getting your Django project working with local objects before trying to integrate Salesforce integration. Using the shell and the ORM are well documented in the Django Tutorials.

**Comment by Dssii3056** [comment]
Thank you for your prompt response @philchristensen 
I really to appreciate you taking the time.

1. Thank you. I will try this out

2. Yes, that makes sense. I guess I just thought that because I was starting the shell from within the venv that I would have access to the data as I did with python manage.py ***

*Thank you for your input. I'm sure there are alot more errors than you pointed out, but I returned the string so I could see the result, as it wasn't showing in my console, and the Django error was truncating the query statement.

--Dan

**Comment by Dssii3056** [comment]
Thanks again for your help!

That did the trick

**Comment by hynekcer** [comment]
The example.models is not an example of a recommended practice on the first place, but also an example of mix of interesting supported features. E.g. Contact uses a Django style lowercase names with underscores (style used by inspectdb) and Account uses camel-case names typical for Salesforce API. It is demonstrated that these styles can be combined, but it is really not recommended to mix them.

Try something simple with the example model. Then very soon export your real database structure by inspectdb. Try anything with that huge ~2 MB models.py file. It is perfect for initial development. An incorrectly simplified model is a frequent source of later errors. Writing a model for Salesforce by hand requires even more experience.

Custom objects and fields are just as easy as standard fields, thanks to inspectdb. It is not easy to report and to reproduce a bug related to a custom model. (Salesforce customization requires clicking that I don't like.) The same problem can be usually demonstrated on models with standard fields and easily reproduced. A test of fix can be easily written a everybody can the fix easily verify or criticize.

Easy types of querysets are e.g. these

    Contact.objects.filter(account__field_of_account='value')
    Contact.objects.filter(account__field_of_account__in=['value1', 'value2'...])

It is much more complicated to write query sets with filters with a subquery query sets that are both compiled into one SOQL request.


    subquery = Contact.objects.filter(...).values('account_id')
    qs = Account.objects.filter(pk__in=subquery).select_related('Owner')

There are many restrictions described in SOQL reference. I am contending to claim today that 90 % of examples in SOQL reference guide are supported by django-salesforce or in the development branch [hynekcer/django-salesforce ping_connection](https://github.com/hynekcer/django-salesforce/tree/ping_connection), written yesterday, but much more querysets with subqueries are unsupported by SOQL. They must be rewritten by evaluating the subquery to a list.
