### ISSUE TITLE
ImproperlyConfigured: 'salesforce.backend' isn't an available database backend

### ISSUE THREAD

**Issue by Connotating** [django-salesforce/django-salesforce#246]
In Django 3.0a1/b1 is there another engine to switch to?

Error:
```
django.core.exceptions.ImproperlyConfigured: 'salesforce.backend' isn't an available database backend. Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
```

```
'salesforce': {
				'ENGINE': 'salesforce.backend', # what replaces this?
				'CONSUMER_KEY': 'XXX',
				'CONSUMER_SECRET': 'YYY',
				'USER': 'user@user.com',
				'PASSWORD': 'password+token',
				'HOST': 'https://salesforceinstance.com',
				},
```

**Comment by hynekcer** [comment]
That error message means that you can not import the module `salesforce.backend.base`. (The rest of the message is for standard backends.) Try the import alone on the command line. If needed, sent the traceback: `python manage.py shell` and  
`>>> import salesforce.backend.base` 

Do you use the latest django-salesforce 0.9? It is necessary for Django 3.0.

**Comment by philchristensen** [comment]
That looks fine. I’d bet the package isn’t installed properly. Try running python and see if you can “import salesforce”

**Comment by Connotating** [comment]
Thank you, a quick update was all it needed.
