### ISSUE TITLE
Enable Github Sponsors?

### ISSUE THREAD

**Issue by stefanfoulis** [django-salesforce/django-salesforce#257]
This library has made my programming life so much better. I don't have to worry about all the nitty gritty details of the salesforce api. I am soooo glad it exists.

How about enabling Github Sponsors (https://github.com/sponsors) so people who can't contribute by PRs or by answering questions have a way to give something back to the project?

(Or patreon, or something similar)

**Comment by philchristensen** [comment]
I’m ready to use GitHub contributors as soon as it supports overseas developers like @hynekcer ... Last time I tried it only supported US devs.

**Comment by philchristensen** [comment]
Whoa, I *just* saw an update that GitHub Sponsors is now available in the Czech Republic.

**Comment by hynekcer** [comment]
Yes, Thanks, I have just yesterday submitted the Github sponsors forms, The request should by only waiting for approval. Previously I have checked the list of only 31 supported countries on Monday and my country was not there when I received a welcome message from Github.

**Comment by philchristensen** [comment]
Looks like the Sponsors link is up and @stefanfoulis and I are the inaugural members!

Years ago @hynekcer started with an interesting hack I had created to avoid having to use Salesforce at work, and has transformed it into a full-fledged enterprise-quality library. I don't really code on this anymore, but I'm extremely proud to contribute in any way I can!
