### ISSUE TITLE
how to create a model class for Salesforce custom object 

### ISSUE THREAD

**Issue by patelurvesh995** [django-salesforce/django-salesforce#270]
I are trying to learn the Django-salesforce python library and  I am new to python Django and salesforce. I follow the following GitHub library https://github.com/django-salesforce/django-salesforce and I follow the following step https://pypi.org/project/django-salesforce/ in python. and I got successfully run my project, But now I am confused because I can't access the custom field of salesforce object can you tell me how can I access the custom field of standard objects like account, contact, etc. I try it but I got following error 

I have a query regarding the below point.

Here is my code :
class Contact(SalesforceModel):

    account = models.ForeignKey(Account, on_delete=models.DO_NOTHING,
                                blank=True, null=True)  # db_column: 'AccountId'
    name = models.CharField(max_length=121, sf_read_only=models.READ_ONLY,
                            verbose_name='Full Name')
    Loan_Amount__c = models.IntegerField(max_length=121, blank=True, null=True)

    def __str__(self):
        return self.name

ERRORS:
webapp.Contact.Loan_Amount__c: (fields.E002) Field names must not contain "__".

can you tell me how can I access the custom field of salesforce standard object or can give a sample code for this ?.

and I have 1 more question about how can we create a model class for custom Salesforce objects. I have created a class for the custom object but it shows me an error.

class NewClient__c(SalesforceModel):

    ClientName = models.CharField(max_length=255)
    Name = models.CharField(max_length=121, sf_read_only=models.READ_ONLY,
                            verbose_name='Full Name')
    email = models.EmailField(blank=True, null=True)

    def __str__(self):
        return self.Name

whenever I put __c in the class name it shows me the following error. Without __c I can communicate with salesforce objects its mandatory for salesforce ?.

ERRORS:
webapp.NewClient__c: (models.E024) The model name 'NewClient__c' cannot contain double underscores as it collides with the query lookup syntax.

can help me solve this error or do you have a and sample code to retrieve data from a custom object in Django.

**Comment by hynekcer** [comment]
Field names and class names can not contain two consecutive underscores in Django, because '__' has a special meaning in queries, very similar to a dot expressions.

See https://docs.djangoproject.com/en/3.0/topics/db/models/#field-name-restrictions

The fix is easy

``` python
class Contact(SalesforceModel):
    ...
    loan_amount = models.IntegerField(max_length=121, db_column='Loan_Amount__c', blank=True, null=True)

class NewClient(SalesforceModel):
    ....
    Meta:
        db_table = 'NewClient__c'
```
