### ISSUE TITLE
Querying Salesforce DB from the Django Shell

### ISSUE THREAD

**Issue by divurgentuser** [django-salesforce/django-salesforce#272]
Hi, I am new to this awesome project. 

Trying to integrate to the Salesforce db/connected app. I want to do a simple ORM query of the Salesforce database.

- I believe my auth worked because I get all the models when I run `python3 manage.py inspectdb --database=salesforce`.
- I can open the Django shell and run `from salesforce import SalesforceModel` etc. 

What do I need to import import? How do I do simple Users.objects.all() or Contact.objects.all() ?

Thanks for any example code

**Comment by philchristensen** [comment]
It’s exactly what you describe, there’s nothing different than using any other kind of Django model.

**Comment by divurgentuser** [comment]
> It’s exactly what you describe, there’s nothing different than using any other kind of Django model.

When I try to import the models, I get errors. I can't import the models listed in inspectdb. How can I import the models to ultimately read data from the Salesforce DB?

from salesforce.models import User
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name 'User' from 'salesforce.models'

**Comment by philchristensen** [comment]
You’ll need to create a models file and import from that. This is all pretty much basic Django stuff, so you may want to review the Django tutorial as well.

**Comment by divurgentuser** [comment]
> You’ll need to create a models file and import from that. This is all pretty much basic Django stuff, so you may want to review the Django tutorial as well.

Thanks for your time Phil.

I know I can run a command like this  `python3 manage.py inspectdb --database=salesforce > models.py`

But I already am integrating Salesforce into a deployed app with a PostgresDB. 

So do I add the new models to my existing models.py file? Or create a new one and point to it somehow? Or how do I otherwise manage having both a Salesforce DB and a traditional DB?

**Comment by philchristensen** [comment]
That seems to vary quite widely. Some people create a whole app for their Salesforce models (this is where i’d suggest you start), others split them up by use case, it really depends. It’s pretty much a Django project planning question, IMO.

**Comment by hynekcer** [comment]
It is very similar to [multiple databases in Django](https://docs.djangoproject.com/en/3.0/topics/db/multi-db/) with normal database backends. A database router can select a database that will be used for reading and writing data. All people that I know use a recommended database router `DATABASE_ROUTERS = ["salesforce.router.ModelRouter"]` and usually only one salesforce database and its name is "salesforce".

The differences are:

* All model that are descendants of `salesforce.models.Model` use the salesforce database by default.
* All model that are descendants of only `django.db.models.Model`, but not `salesforce.models.Model` can use only non-salesforce databases, by default the `"default"` database.

You can not create foreign for cross references between different databases, but the keys can be saved eventually saved as normal fields. 
That is reason why I would recommend to separate the models to two applications. One of them will have only models.py file and the models will be imported into views and forms of the main application.
