### ISSUE TITLE
Django 3.1 Support

### ISSUE THREAD

**Issue by awartani** [django-salesforce/django-salesforce#274]
Thanks, we're still testing this library and it looks great so far

We're wondering how can we use it with Django 3.1?

**Comment by philchristensen** [comment]
Your timing is excellent, we’ll have an update for 3.1 shortly, within a day or two.

-Phil

**Comment by awartani** [comment]
That's awesome! thanks

**Comment by philchristensen** [comment]
Fortunately support was already there, we just needed to tweak some things and make a new release. v3.1 has been released to PyPI

**Comment by hynekcer** [comment]
New Django development version are usually supported by django-salesforce before Django Alpha release, maybe by a patch release or only in the repository. Unofficial support for Django 3.1 development versions was ready in django-salesforce 1.0 released on May 1, 2020.

The preliminary compatibility could be broken sometimes again still by a Django Alpha release. (I don't remember later problems after any Django Beta or RC.)

I will try to release new minor versions short time before a new Django final. It will declare the final compatibility. e.g. django-salesforce 3.2 in the last weeks of March 2021 between Django 3.2 RC1 and Django 3.2.0 final.
