### ISSUE TITLE
SalesforceAuthError: oauth failed

### ISSUE THREAD

**Issue by VadymKhodak** [django-salesforce/django-salesforce#277]
I've got this error message:

> SalesforceAuthError: oauth failed: <salesforce_username>: {"error":"unsupported_grant_type","error_description":"grant type not supported"}

`settings.py`
```python
DATABASES = {
    'salesforce': {
        'ENGINE': 'salesforce.backend',
        'CONSUMER_KEY': config.SALESFORCE_CLIENT_ID,                
        'CONSUMER_SECRET': config.SALESFORCE_CLIENT_SECRET,    
        'USER': config.SALESFORCE_LOGIN,
        'PASSWORD': config.SALESFORCE_PASSWORD,
        'HOST': config.SALESFORCE_BASE_URL,  # 'https://sandbox-name.lightning.force.com/'
    }
}
```
`models.py`
```python
from salesforce import models


class Account(models.SalesforceModel):
    Id = models.CharField(max_length=255)

    class Meta(models.Model.Meta):
        db_table = 'Account'
        verbose_name = 'Account'
        verbose_name_plural = 'Accounts'
```

I tried to get this when I got this error message:
`>>> Account.objects.count()`

Could you please help me with what I did wrong?

python 3.8
django==3.0.10
django-salesforce==3.1

**Comment by philchristensen** [comment]
Can’t really tell as you’re referring to this `config` object. You’ll want to revisit the instructions on setting up your API keys.

**Comment by VadymKhodak** [comment]
Thank you for your quick response.
It was my failure.
`'PASSWORD': config.SALESFORCE_PASSWORD + config.SALESFORCE_SECURITY_TOKEN,`
and I used wrong HOST.

I've just started using this library and I really like it.
Thank you for doing this.

**Comment by philchristensen** [comment]
Glad you got it figured out!
