### ISSUE TITLE
Continuous testing for Django 4.0 until the final release

### ISSUE THREAD

**Issue by hynekcer** [django-salesforce/django-salesforce#292]
Fixed an important blocking change in Django 4.0 alpha 1 caused by removing the customizable `where` parameter and also `where_class` attribute from ` django.db/models.sql.query.Query`. (Django ticket 32951: [Remove Query.where_class in favor of using WhereNode directly](https://code.djangoproject.com/ticket/32951))

> Release notes - Miscelaneous
> * The where_class property of django.db.models.sql.query.Query and the where_class argument to the private get_extra_restriction() method of ForeignObject and ForeignObjectRel are removed. If needed, initialize django.db.models.sql.where.WhereNode instead. ([Django 4.0 Release notes](https://docs.djangoproject.com/en/dev/releases/4.0/#s-miscellaneous))

Changed call parameters for EXPLAIN command, more strict check for TimeField in Django 4.0

That all is fixed by ...

---

Django 4.0 supports only Python 3.8, 3.9 and 3.10. That is not supported by our current Travis CI configuration. (Old Python in Ubuntu 18, old Python in `pyenv` that can not be easily updated. Compilation of Python or installing by Anaconda on every test is an overkill.) I rewrote Travis configuration to virtual Ubuntu 20 Focal Fossa with builtin Python support. (used Python 3.6, 3.9 and the default 3.8) The important change is to set [Limit concurrent jobs](https://docs.travis-ci.com/user/customizing-the-build/#limiting-concurrent-jobs) to `1` because all tests share the same Salesforce database. That should be updated in settings of django-salesforce/django-salesforce repository in Travis user interface before running a new test.

---

This issue can close when Djago 4.0rc1 will be released and tested.

**Comment by hynekcer** [comment]
The version 4.0 can be released just now. I updated README etc. by the last two commits in the main branch: 654fcaaa87479f80505fd9ebc397dd985348af95. The current draft for v4.0 is "Django 4.0 support".

(A draft with postponed features is "Migrations can manage SFDC instances" and it should wait.)

**Comment by philchristensen** [comment]
Sounds great! I’ll do that today.

**Comment by philchristensen** [comment]
Released and uploaded to https://pypi.org/project/django-salesforce/4.0/
