### ISSUE TITLE
sf_params

### ISSUE THREAD

**Issue by picousse** [django-salesforce/django-salesforce#301]
I just connected with a salesforce instance, and did a full inspect of the database.

I got some weird fields like XJSON in some of the models.

Anyway, for now, I commented those out, just to try a bit of stuff.

However whenever I want to fire a query
```
TestTable.objects.using("salesforce").all()
```

, I get

```
AttributeError: 'Query' object has no attribute 'sf_params'
```

Tips and tricks what I might be doing wrong?

**Comment by picousse** [comment]
I screwed up.
Just for reference.
I think the inspect command spit out that I should use
```
from django.contrib.gis.db import models
```

for the models. 
However it  should be:


```
from salesforce import models
```

**Comment by hynekcer** [comment]
Every type of Salesforce field is supported. Maybe it could be not intuitive to work with fields that have no support by a widget in Django e.g. a Multi-Select Picklist, but at least every builtin object type is tested that it can be read and written without errors.
