### ISSUE TITLE
Multi select Picklist to django model: inspectdb

### ISSUE THREAD

**Issue by picousse** [django-salesforce/django-salesforce#303]
Hi,
I'm encountering a multiple picklist selector field.
Is there any integration for these fields in django-salesforce?

E.g. Is there an integration to fetch the possibilities of the picklist?
A quick search showed  me that there are some REST API endpoints where I could get the possibilities from.

e.g. https://developer.salesforce.com/forums/?id=906F000000092QuIAI

**Comment by hynekcer** [comment]
The title "Picklist" is too broad. It is not clear enough if you mean a Multi-Select Picklist by your term "multiple picklist selector field" and not a simple Picklist.

A) simple Picklist
A picklist has an equivalent Django field type: a CharField with `choices` option. This is supported by introspection by `inspectdb` command. You automatically get in the model the defined choices values. Supported operators for picklist in SOQL are `=`, `!=`, `IN`, `NOT IN` and their negation. Therefore also their equivalents in Django querysets are supported. Operators `<`, `<=`, `>`, `>=` are  only partly supported by SOQL (after my intervention) but negation of these operators is unsupported like `not (field > 'value')`.

(I will continue about Multi-Select Picklist)

**Comment by picousse** [comment]
Oke, thanks, and sorry for the unspecific topic.
The problem is I'm not in control of the SalesForce setup, and I'm not really used to using this in practice.

However I do need to work with it, we choose to use django salesforce, because of it's ease of use.

the inspectdb command works really well, but I'm just not getting the choices in the multiselect thingy.

**Comment by picousse** [comment]
oke thanks a lot for the feedback and tips and tricks.
