### ISSUE TITLE
SOQL for ContentDocument not working

### ISSUE THREAD

**Issue by sebastian-philipp** [django-salesforce/django-salesforce#314]
Due to some strange permission issues, calling `ContentDocument.objects.get(id='069XYZ')` raises a `DoesNotExist`:

```
>>> from app.salesforce import ContentDocument
>>> ContentDocument.objects.get(id='069XYZ')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(
app.salesforce.ContentDocument.DoesNotExist: ContentDocument matching query does not exist.
```

but requesting the individual object works out: 

```
>>> from django.db import connections
>>> r = connections['salesforce'].connection.handle_api_exceptions(
...             'GET', 'sobjects/ContentDocument/069XYZ'
... )
>>> r.json()
{'attributes': {'type': 'ContentDocument', 'url': '/services/data/v54.0/sobjects/ContentDocument/069XYZ'}, 'Id': '069XYZ', ...}
```

Would something like a special handling for `if re.matches(soql, "SELECT .* FROM ([^ ]+) WHERE id = ([^ ]+)"` would work out in the driver.py?

**Comment by hynekcer** [comment]
I can not reproduce your problem. Maybe you try it as a different user.

Even if you are a System Administrator you do not see the `ContentDocument` object by a SELECT command if the user did not changed a default permission "No Access" to "Collaborators" or "Viewers". The method `get()` use a standard SELECT command because it should use general filters, not only directly by ID.

It is interesting that it is possible to access somebody else's document with "No Access" if you know the ID. If you find that it does not correspond to [documentation about ContentDocument permissions](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_contentdocument.htm) you can ask Salesforce support.

**Comment by hynekcer** [comment]
@sebastian-philipp If you had such advanced question or you wish this framework to be better, for example for me to describe some features not yet documented, or you just like it as it is, please click the Sponsor button...

e.g.: You can create a web application with django-salesforce that ask a user of your organization for consent to work with Salesforce impersonating him/her in this session. (Redirect to login, ask for permission, wait for consent or rejection and redirect back.) Django-salesforce implements authentication backend classes salesforce.auth.DynamicAuth and salesforce.auth.RefreshTokenAuth that are useful for it. I wrote an example application.

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp If you had such advanced question or you wish this framework to be better, for example for me to describe some features not yet documented, or you just like it as it is, please click the Sponsor button...

django-salesforce is pretty great actually. 

> 
> e.g.: You can create a web application with django-salesforce that ask a user of your organization for consent to work with Salesforce impersonating him/her in this session. (Redirect to login, ask for permission, wait for consent or rejection and redirect back.) Django-salesforce implements authentication backend classes salesforce.auth.DynamicAuth and salesforce.auth.RefreshTokenAuth that are useful for it. I wrote an example application.

Not really pretty, but for now my workaound looks like:

```python
class DirectGetManager(SalesforceManager[T]):
    def get(self, *args, id=None, **kwargs) -> 'T':
        if id is not None and not args and not kwargs:
            relative_url = f"sobjects/{self.model._meta.db_table}/{id}"
            try:
                data = (
                    connections['salesforce']
                    .connection.handle_api_exceptions('GET', relative_url)
                    .json()
                )
            except SalesforceError as e:
                if e.response.status_code == 404:
                    raise self.model.DoesNotExist
                raise
            data = {
                field.name
                if not isinstance(field, RelatedField)
                else f'{field.name}_id': data[field.db_column]
                if field.name != 'id'
                else "Id"
                for field in self.model._meta.concrete_fields
            }
            return self.model(**data)
        if id is not None:
            kwargs['id'] = id
        return super().get(*args, **kwargs)
```

**Comment by hynekcer** [comment]
How can you get a primary key of a not shared ContentDocument of another user? I think that it is not possible by the API. Maybe it is a link from another object that has its own more specific sharing rules?

If it is possible or you know another example where the GET `.../sobjects/<object type>/<primary key>` is necessary then I will implement a solution.
