### ISSUE TITLE
inspectdb doesn't create custom objects tables.

### ISSUE THREAD

**Issue by weinbergdavid** [django-salesforce/django-salesforce#325]
I run `python manage.py inspectdb`, and I got all the Salesforce models with all the fields, including custom fields. But the command doesn't inspect models that are custom models.

Thanks in advance.

**Comment by hynekcer** [comment]
That is strange. It requires more information if is it really a bug. First try to create a new very simple custom object, assign user permissions for it to all user profiles or at least to the profile used to run django-salesforce or run inspectdb as a system administrator.

Two causes are possible:
A) User permissions: If a user can not use an object then the it can not be introspected.

B) Maybe the object uses something very special that caused a bug. Try to create a model only for one object:
```
python manage.py inspectdb --database=salesforce YourObject__c
```
Maybe you will see an empty file models.py or more probable you see also a comment about an error. That could be a useful clue to reproduce the problem.

Finally: describe a minimal custom object that can be used to reproduce the problem.

**Comment by hynekcer** [comment]
@weinbergdavid Can you confirm or withdraw this your issue please?
