### ISSUE TITLE
Document the need to enable Username-Password flow

### ISSUE THREAD

**Issue by matiboy** [django-salesforce/django-salesforce#326]
> Username-password flows are blocked by default in orgs created in Summer ‘23 or later

Quoted from Salesforce OAuth and OpenID Connect Settings

**Comment by hynekcer** [comment]
Thanks for the documentation patch.

I use also a refresh token OAuth flow with multi-factor authentication in some project. This could be my next step: to write a  documentation for it and a simple demo front end page how to get that token.

**Comment by matiboy** [comment]
Since I just did something like that, I can maybe help there?

**Comment by hynekcer** [comment]
OK. I will write more tomorrow.
