### ISSUE TITLE
Version 5.0 for Django 5.0

### ISSUE THREAD

**Issue by hynekcer** [django-salesforce/django-salesforce#330]
A change log for django-salesforce 5.0 is very short, but the new release for Django 5.0 was necessary.

* Add: Support for Django 5.0
* Add: Monitoring 'api_usage' from 'Sforce-Limit-Info' API response header #317

Please put it on PyPI.

**Comment by philchristensen** [comment]
Released v5.0 here on and PyPI: https://pypi.org/project/django-salesforce/5.0
