### ISSUE TITLE
More information in one place about license key

### ISSUE THREAD

**Issue by DmytroLitvinov** [django-salesforce/django-salesforce#332]
Hi @hynekcer ,

Since our project depends on that library which you support (and we really appreciate your efforts on it) - it would be nice if we can have one place where we can read more info about licensing and support of package

. Right now I checked with "git blame" commits to find out when it first time was mentioned and found out that it was mentioned 7 months ago, also some part of information was mentioned in [GitHub release](https://github.com/django-salesforce/django-salesforce/releases/tag/v5.0) about how to get license key and some other part how it works I read in code via function `check_license_in_latest_django`.

My proposal for that one - providing in README separate section about licensing, the reason behind it, explain how it will affect users, how-to get keys and use it. The more transparent it will be, the more chances to get funded (personal opinion), but anyway talking about personal issue - we would love to know more details so I can raise that question with the upper-management team about funding but I need more details about it.

**Comment by hynekcer** [comment]
A better final solution is described in Wiki  [Release cycle and Licenses](https://github.com/django-salesforce/django-salesforce/wiki/Release-cycle-and-Licenses). (Every version is free after the first 8 months, but LTS versions will be then locked again for 8 months, e.g. in 5.1 and then free again after 5.2 for the final 12 months.)
