### ISSUE TITLE
Limit Django compatibility on package level

### ISSUE THREAD

**Issue by lociii** [django-salesforce/django-salesforce#338]
Currently the package defines itself as compatible with `django>=2.1` in [setup.py ](https://github.com/django-salesforce/django-salesforce/blob/main/setup.py). However on runtime, the [initialization](https://github.com/django-salesforce/django-salesforce/blob/main/salesforce/backend/__init__.py) makes additional checks that prevent it from working with Django 5.1.

This should ideally be prevented and the package should already report to be incompatible with 5.1  
Otherwise, this might break installations that upgrade Django in good faith that nothing is blocking and then break when actually running them.

Thanks!

**Comment by hynekcer** [comment]
Thanks for comments and remind that the new version is urgent, although I'm busy now.

Everybody could easily verify that the current version 5.0.2 (from May 2024) works with Django==5.1rc1. If I would restrict Django < 5.1 then nobody can install a pre-release. It is even more complicated for people with MIT license but without a configured license key. They should try it, read the message decide what is the best way for them. Maybe they should only fix the configuration after installing Django.

The best solution is if I would manage to release all new versions in time. The version 5.1 will be probably today or by the end of August.

**Comment by hynekcer** [comment]
Fixed by #340. Thanks.

**Comment by hynekcer** [comment]
Reopen. A solution should be written that does not break development for a new Django. I run tests for new Django almost every month because it is easier to fix compatibility continuously if possible. The version restriction must be bypassable without changing anything in the source repository.

**Comment by lociii** [comment]
The restriction in `setup.py` is only limiting the package installation. It does not have an effect on running tests against the source code in the repository.  
You can still use GitHub actions, run it locally, etc. It will just prevent people from installing the package alongside an unsupported Django release.

**Comment by hynekcer** [comment]
The project run tests for many Django/Python versions by [tox](https://tox.wiki) test automation. It installs compatible versions of all dependencies for particular configurations. If anything in a test configuration ([tox.ini file](https://github.com/django-salesforce/django-salesforce/blob/main/tox.ini)) is changed then these virtual environments are automatically recreated according to specifications including `install_requires` in `setup.py`. That was a problem in Februar 2018 when I forgot a line `install_requires=['django>=1.10,<2.2'] + ...`. All tests for a new Django 2.2 seemed to pass long time until the final edition was approaching and then many issues appeared together.

**Comment by hynekcer** [comment]
Fixed by 781bd4c. The string `',<5.2'` is now added conditionally.
