### ISSUE TITLE
Impossible to resolve relationship caused by several driving SObject

### ISSUE THREAD

**Issue by pirhoo** [django-salesforce/django-salesforce#43]
Hi,

the following code throws me a curious error from SalesForce :

``` python
# Get all voyages for the given account
voyages = DemandeDeFinancement.objects.all().filter(Account__rne='0930897V')
```

Results on :

> A driving SObject type has already been set, all other entity types in the FROM clause must be relationships to the initial object.  The driving object is Demande_de_financement__c

Any clue? 

This library is still amazing :)

Best,
Pierre

**Comment by hynekcer** [comment]
The issue is fixed now in the latest master. (it should work with your original filter)
