### ISSUE TITLE
Setting up a test database

### ISSUE THREAD

**Issue by tvanesse** [django-salesforce/django-salesforce#98]
As mentioned in the README, connecting to the SFDC resources can really become time consuming when it comes to repeat unit tests over and over in a project using django-salesforce.

I am trying to set up a testing database (SQLite3) to speed up my development but I am unsure of how to dump the real Salesforce schema into this new database. Could you provide some instructions to work it out? I think these instructions would be nice to have in the README as well.

**Comment by philchristensen** [comment]
You just need to change your DB engine during testing to use SQLite; this is a technique you could use for speeding up tests with *any* backend. Here's a relevant SO link:

http://stackoverflow.com/questions/6353124/running-django-tests-with-sqlite

**Comment by tvanesse** [comment]
It was that easy. Thank you.
