### ISSUE TITLE
Incompatibility with Django 1.8 

### ISSUE THREAD

**Issue by josephmosby** [django-salesforce/django-salesforce#99]
Per Django 1.8 docs: 

    ### Database backend API

    The following changes to the database backend API are documented to assist those writing third-party backends in updating their code:

    BaseDatabaseXXX classes have been moved to django.db.backends.base. Please import them from the new locations:

I am working on a patch for this. Looks to be a simple fix of switching imports out.

**Comment by philchristensen** [comment]
That's great. Glad they're starting to think about backend developers.

**Comment by hynekcer** [comment]
I used your pull request in my #102 which solves more related problems with Django 1.8, but also not all. Maybe it is enough for you. More info in my Readme.
